heuristic: "hit_closest_ball"
seed: 0
env_type: "Cuesim/ThreeBallHard-Cuelearner"
trainer:
  log_dir: "experiments/current/heuristic_closest_ball"
  max_steps: 20000000
  buffer_size: 20000000
  start_steps: 10000
  update_after: 1000
  update_every: 1000
  grad_steps: -1
  act_noise: 0.0025
  eval_steps: 1000
  eval_every: 10000
  advice_noise: 0.0025
  advice_q_threshold: 0.25
  advice_probability: 0.5
  advice_usage_limit: -1
  # checkpoints
  policy_checkpoint_options:
    save_best: true
    save_last: true
    save_period: 10000
  print_every: 10000
policy:
  type: "ddqn"
  args:
    batch_size: 100
    discount: 0.0
    policy_noise: 0.0
    noise_clip: 0.2
    target_update_freq: 2
    hidden_sizes_critic: [400, 400, 400, 300, 300, 300]
    training_sampling: "argmax"
    # optimizer
    optimizer: "sgd"
    learning_rate: 0.1
    weight_decay: 0.
    gradient_clipping: 0.5
    fit_policy: "fixed"
